### PR TITLE
Convert section title to link

### PR DESCRIPTION
**Pull request by shinkhouse**
Hi there, 

Really impressed with this project. One thing I noticed is the status page could potentially become very long.  Because of this, I converted the probe section h3 to a link so if user wanted to jump to specific section, they could. 

For example, going to the below link would direct them to the internal section identified by the probe id.
http://localhost:8080/#internal

### CODE REVIEW

**Comment by valeriansaliou** [comment]
Hey Samuel,

Thank you for the kind words! Looks good to me, merging this now 👍

**Comment by valeriansaliou** [comment]
Quick note: I've made a minor change to restore the semantic structure of the page (ie. usage of title elements) in: 2afc356e4338cb0d6c8a51dd10132d28e7aa9f8d + some minor style improvements.

**Comment by valeriansaliou** [comment]
Released: https://github.com/valeriansaliou/vigil/releases/tag/v1.20.1

I'm in the process of building the binaries.

**Comment by shinkhouse** [comment]
Thanks for merging my first pull request on a Github project!

**Pull request merged**
