### PR TITLE
ci: use Github Actions

### LINKED ISSUE #66: Move away from Travis CI to GitHub Actions
Travis CI has removed free CI minutes for OSS projects. Time to move to GH Actions, as builds will not run anymore on Travis.

### PR DESCRIPTION
**Pull request by zllovesuki**
This should fix #66. Some tweaking may be required.

### CODE REVIEW

**Comment by valeriansaliou** [comment]
Great, thanks. Let me know when it's ready to review & merge, as I see that it's still a draft.

**Comment by zllovesuki** [comment]
Testing on my branch works, ready for review now 😊

**Comment by zllovesuki** [comment]
https://github.com/zllovesuki/vigil/runs/1524740661

**Comment by valeriansaliou** [comment]
Perfect, thanks a ton! Merging, I'll update the Travis badge afterwards. 🙂

**Pull request merged**
