### PR TITLE
Update Dockerfile to include libcurl3

### PR DESCRIPTION
**Pull request by aldisanta**
Hi, this was pull request related to following [issue](https://github.com/valeriansaliou/vigil/issues/28).

### CODE REVIEW

**Comment by aldisanta** [comment]
Travis fail, suspected issue: [lettre](https://github.com/lettre/lettre/issues/343).

Travis fail

**Comment by valeriansaliou** [comment]
Can you rather exclude the lettre feature in the initial Dockerbuild? This will also work in a simpler way, as not much ppl use the email notifier AFAIK.

**Comment by valeriansaliou** [comment]
No, not this way. You can specify features to cargo when installing from Crates, that's how I'd do it. Do not edit Cargo.toml right away just for Docker

**Comment by aldisanta** [comment]
> Can you rather exclude the lettre feature in the initial Dockerbuild? This will also work in a simpler way, as not much ppl use the email notifier AFAIK.

So are we rather remove `notifier-email` feature ? 
If it's, I have few changes:

1. Cargo.toml has been updated to remove `notifier-email` as feature, the original file located here: `Cargo.toml.notifier-email`.
2. Docker based on `rustlang/rust:nightly` on 1st stage build.
3. Running `cargo clean && cargo build --release` instead of `cargo install vigil-server`.

**Comment by aldisanta** [comment]
> No, not this way. You can specify features to cargo when installing from Crates, that's how I'd do it. Do not edit Cargo.toml right away just for Docker

so that'll be 
```
cargo install --no-default-features --features "notifier-twilio","notifier-slack" vigil-server
```
?

Anyway, thank you for pointing me, I'm new to Rust & this is my first contribution attempt on public repo.

**Comment by rongfengliang** [comment]
@aldisanta @valeriansaliou   seems  use  specific version of  nightly will better

 like this 

```code
FROM rustlang/rust:nightly AS build

WORKDIR /app

COPY . /app

RUN rustup install nightly-2019-01-17

RUN rustup   default nightly-2019-01-17

RUN cargo -V

RUN cargo build --release
```

**Comment by aldisanta** [comment]
> @aldisanta @valeriansaliou seems use specific version of nightly will better
> 
> like this
> 
> ```
> FROM rustlang/rust:nightly AS build
> 
> WORKDIR /app
> 
> COPY . /app
> 
> RUN rustup install nightly-2019-01-17
> 
> RUN rustup   default nightly-2019-01-17
> 
> RUN cargo -V
> 
> RUN cargo build --release
> ```

Thanks @rongfengliang .

Previous PR was using `nightly-2019-05-14`, but perhaps using `buildpack-deps:stretch` as base image was bit too much. I'll just wait for @valeriansaliou, it appears he's still busy.

**Comment by valeriansaliou** [comment]
Okay, roll everything back and pin the Rust nightly version for now, that'll do.

**Pull request merged**
